apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-website-api
  template:
    metadata:
      labels:
        app: personal-website-api
    spec:
      containers:
      - name: back-end
        image: benldouthwaite/base-api:v0.0.9
        ports:
        - containerPort: 8081
---
apiVersion: v1                  # API version
kind: Service                   # Type of kubernetes resource
metadata:
  name: personal-website-api # Name of the kubernetes resource
spec:
  type: NodePort               # Exposes the service by opening a port on each node
  selector:
    app: personal-website-api     # Any Pod matching the label `app=personal-website-api` will be picked up by this service
  ports:                        # Forward incoming connections on port 80 to the target port 80 in the Pod
  - name: http
    port: 8081
    targetPort: 8081
    nodePort: 30002
    protocol: TCP