apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # Set the deployment name
spec:
  replicas: 2
  selector: # Defines how the deployment find which pods to manage
    matchLabels:
      app: nginx-label
  template:
    metadata:
      labels:
        app: nginx-label # Pod label
    spec: # Pod's template spec
      containers:
        - name: hello-world-nginx
          image: nginx
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - containerPort: 80
      volumes:
        - name: nginx-config
          configMap:
            name: config-service-nginx
