{
 "title": "New dashboard Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Home (/) Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_response_time_seconds_bucket{service=\"go-hello-service\", path=\"/\"}[5m]))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, rate(http_response_time_seconds_bucket{service=\"go-hello-service\", path=\"/\"}[5m]))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.999, rate(http_response_time_seconds_bucket{service=\"go-hello-service\", path=\"/\"}[5m]))",
     "legendFormat": "P99.9"
    },
    {
     "expr": "histogram_quantile(1, rate(http_response_time_seconds_bucket{service=\"go-hello-service\", path=\"/\"}[5m]))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "Status Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(response_status[1m])", "legendFormat": "{{status}}" }
   ]
  }
 ]
}