apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dummy-ui-and-api-test
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: front-end
        image: benldouthwaite/personal-website:latest
        ports:
        - containerPort: 8080
      - name: back-end
        image: benldouthwaite/base-api
        ports:
        - containerPort: 8081
